- hosts: localhost
  tasks:
    - yum_repository:
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        name: "docker-ce"
        description: "Docker-ce repo"
        gpgcheck: no

    - package:
        name: "python3"
        state: present

    - package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present


    - service:
        name: "docker"
        state: started
        enabled: yes
