- hosts: all
  vars:
      - dvd_dir: "/dvd1"
  tasks:
    - file:
        state: directory
        path: "{{ dvd_dir }}"

    - mount:
        src: "/dev/cdrom"
        path: "{{ dvd_dir }}"
        state: mounted
        fstype: iso9660

    - yum_repository:
        baseurl: "{{ dvd_dir }}/AppStream"
        name: "dvd1"
        description: "AppStream dvd"
        gpgcheck: no

    - yum_repository:
        baseurl: "{{ dvd_dir }}/BaseOS"
        name: "dvd2"
        description: "BaseOS dvd"
        gpgcheck: no

    - yum_repository:
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        name: "docker-ce"
        description: "Docker-ce repo"
        gpgcheck: no

    - package:
        name: "python3"
        state: present

    - package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present

    - pip:
        name: "docker-py"

    - service:
        name: "docker"
        state: started
        enabled: yes
