- hosts: localhost
  tasks:
    - name: removing config file
      shell: "rm -rf $HOME/.kube/config"
      ignore_errors: yes
    - name: initialising kubeadm
      shell: "kubeadm init --pod-network-cidr=10.244.0.0/16"
      ignore_errors: yes    
    - name: Creating .kube directory
      file:
         name: "$HOME/.kube"
         state: directory

    - name: Copy kube config
      copy:
         src: /etc/kubernetes/admin.conf
         dest: $HOME/.kube/config
         remote_src: yes

    - name: changing owner permission
      shell: "chown $(id -u):$(id -g) $HOME/.kube/config"
    - name: Flannel Command
      shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
      ignore_errors: yes
    - name: untaint masternode
      shell: "kubectl taint nodes localhost.localdomain node-role.kubernetes.io/control-plane:NoSchedule-"
      ignore_errors: yes
    - name: tekton
      shell: "./configure.sh"
      ignore_errors: yes
